services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    environment:
      - OPENAI_API_KEY
    volumes:
      - .:/app
    command: python -m streamlit run /app/app.py

  test:
    build:
      context: .
      dockerfile: Dockerfile
      target: testing
    volumes:
      - ./:/app
    environment:
      - PYTHONPATH=/app
    command: ptw --ignore=.git --ignore=__pycache__ src tests -- -vv tests/
